# Generated by Django 5.2.7 on 2025-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='horario',
            new_name='schedule',
        ),
    ]
