# Generated by Django 5.2.7 on 2025-11-25 16:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendance_generated",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="project",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="group",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.schedule",
            ),
        ),
    ]
