# Generated by Django 5.2.7 on 2025-10-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_day_profile'),
        ('mentors', '0006_mentorattendance_date_alter_mentor_knowledge_level'),
        ('projects', '0002_auto_20251022_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
        ),
        migrations.AlterField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentors.mentor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
        ),
    ]
