# Generated by Django 5.2.7 on 2025-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_event_attendance_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
