# Generated by Django 5.2.7 on 2025-11-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_day_profile'),
        ('mentors', '0007_rename_registered_by_mentorattendance_confirmed_by_and_more'),
        ('projects', '0002_auto_20251022_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentors.mentor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
        ),
    ]
