# Generated by Django 5.2.7 on 2025-10-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_day_profile'),
        ('projects', '0003_event_schedule_alter_group_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
            preserve_default=False,
        ),
    ]
