# Generated by Django 5.2.7 on 2025-12-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_unused_event_fields"),
        ("projects", "0003_remove_unused_fields"),
    ]

    operations = []
