# Generated by Django 5.2.7 on 2025-12-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_event_cancellation_reason_event_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_generated',
            field=models.BooleanField(default=False),
        ),
    ]
