# Generated by Django 5.2.7 on 2025-11-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_event_date_remove_event_end_date_and_more'),
        ('projects', '0005_event_project'),
    ]

    operations = [
    ]
