# Generated by Django 5.2.7 on 2025-11-25 16:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorattendance",
            name="confirmed_by",
        ),
        migrations.RemoveField(
            model_name="mentorattendance",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="mentorattendance",
            name="is_confirmed",
        ),
        migrations.RemoveField(
            model_name="mentorattendance",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="mentorattendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="mentorattendance",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
