# Generated by Django 5.2.7 on 2025-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='knownledge_level',
            field=models.CharField(choices=[('Basico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20),
        ),
    ]
