# Generated by Django 5.2.7 on 2025-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_remove_mentorattendance_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorattendance',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='mentorattendance',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorattendance',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorattendance',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
