# Generated by Django 5.2.7 on 2025-10-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_alter_mentor_options_remove_mentor_certificate_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='knownledge_level',
            new_name='knowledge_level',
        ),
    ]
