# Generated by Django 5.2.7 on 2025-10-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_day_profile'),
        ('mentors', '0003_rename_knownledge_level_mentor_knowledge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
    ]
