# Generated by Django 5.2.7 on 2025-10-17 17:49

import apps.mentors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.mentors.models.generateCertificatePath),
        ),
    ]
