# Generated by Django 5.2.7 on 2025-10-17 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mentor_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorattendance',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='knowledge_level',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20),
        ),
    ]
