# Generated by Django 5.2.7 on 2025-11-18 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_mentorattendance_date_alter_mentor_knowledge_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorattendance',
            old_name='registered_by',
            new_name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='mentorattendance',
            name='date',
        ),
        migrations.AddField(
            model_name='mentorattendance',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorattendance',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorattendance',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
